-- chay script nay duoi quyen sysdba de tao 1 tk admin thao tac thay the cho sysdba


-- sqlplus sys/your_password@localhost:1521/XEPDB1 as sysdba
ALTER SESSION SET CONTAINER = XEPDB1;
SHOW CON_NAME;
DROP USER admin CASCADE;

CREATE USER admin IDENTIFIED BY "1234"
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

ALTER USER admin ACCOUNT UNLOCK;

GRANT CREATE SESSION TO admin;

GRANT CREATE USER TO admin;
GRANT ALTER USER TO admin;
GRANT DROP USER TO admin;

GRANT GRANT ANY ROLE TO admin;
GRANT GRANT ANY PRIVILEGE TO admin;

GRANT SELECT_CATALOG_ROLE TO admin;

GRANT DBA TO admin;