ALTER SESSION SET CONTAINER = XEPDB1;

-- Xoa tai khoan admin cu neu co
BEGIN
    EXECUTE IMMEDIATE 'DROP USER admin CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

-- Tao tai khoan admin 
CREATE USER admin IDENTIFIED BY "1234"
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

ALTER USER admin ACCOUNT UNLOCK;

-- Cap cac quyen cho admin
GRANT CREATE SESSION TO admin;
GRANT CREATE USER TO admin;
GRANT ALTER USER TO admin;
GRANT DROP USER TO admin;
GRANT GRANT ANY ROLE TO admin;
GRANT GRANT ANY PRIVILEGE TO admin;
GRANT SELECT_CATALOG_ROLE TO admin;
GRANT DBA TO admin;

ALTER SESSION SET CURRENT_SCHEMA = admin;

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(5) CHECK (PHAI IN (N'Nam', N'Nữ')),
    NGAYSINH DATE,
    CMND VARCHAR2(12) UNIQUE,
    QUEQUAN NVARCHAR2(200),
    SODT VARCHAR2(15),
    VAITRO NVARCHAR2(50) CHECK (VAITRO IN (N'Điều phối viên', N'Bác sĩ/Y sĩ', N'Kỹ thuật viên', N'Bệnh nhân')),
    CHUYENKHOA NVARCHAR2(100)
);

CREATE TABLE BENHNHAN (
    MABN VARCHAR2(10) PRIMARY KEY,
    TENBN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(5) CHECK (PHAI IN (N'Nam', N'Nữ')),
    NGAYSINH DATE,
    CCCD VARCHAR2(12) UNIQUE,
    SONHA NVARCHAR2(50),
    TENDUONG NVARCHAR2(100),
    QUANHUYEN NVARCHAR2(100),
    TINHTP NVARCHAR2(100),
    TIENSUBENH NVARCHAR2(500),
    TIENSUBENHGD NVARCHAR2(500),
    DIUNGTHUOC NVARCHAR2(500)
);

CREATE TABLE HSBA (
    MAHSBA VARCHAR2(10) PRIMARY KEY,
    MABN VARCHAR2(10) REFERENCES BENHNHAN(MABN),
    NGAY DATE,
    CHANDOAN NVARCHAR2(500),
    DIEUTRI NVARCHAR2(500),
    MABS VARCHAR2(10) REFERENCES NHANVIEN(MANV),
    MAKHOA VARCHAR2(10),
    KETLUAN NVARCHAR2(500)
);

CREATE TABLE HSBA_DV (
    MAHSBA VARCHAR2(10) REFERENCES HSBA(MAHSBA),
    LOAIDV NVARCHAR2(100),
    NGAYDV DATE,
    MAKTV VARCHAR2(10) REFERENCES NHANVIEN(MANV),
    KETQUA NVARCHAR2(500),
    PRIMARY KEY (MAHSBA, LOAIDV, NGAYDV)
);

CREATE TABLE DONTHUOC (
    MAHSBA VARCHAR2(10) REFERENCES HSBA(MAHSBA),
    NGAYDT DATE,
    TENTHUOC NVARCHAR2(100),
    LIEUDUNG NVARCHAR2(200),
    PRIMARY KEY (MAHSBA, NGAYDT, TENTHUOC)
);

CREATE TABLE THONGBAO (
    MATB NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOIDUNG NVARCHAR2(1000),
    NGAYGIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DIADIEM NVARCHAR2(200)
);

INSERT ALL
  INTO NHANVIEN VALUES ('NV001', N'Nguyễn Văn An', N'Nam', TO_DATE('1985-05-20','YYYY-MM-DD'), '123456781', N'Hà Nội', '0912345671', N'Điều phối viên', NULL)
  INTO NHANVIEN VALUES ('NV002', N'Trần Thị Bình', N'Nữ', TO_DATE('1990-10-12','YYYY-MM-DD'), '123456782', N'TP HCM', '0912345672', N'Điều phối viên', NULL)
  INTO NHANVIEN VALUES ('NV003', N'Lê Văn Cường', N'Nam', TO_DATE('1988-03-15','YYYY-MM-DD'), '123456783', N'Đà Nẵng', '0912345673', N'Điều phối viên', NULL)
  INTO NHANVIEN VALUES ('NV004', N'Phạm Minh Đức', N'Nam', TO_DATE('1982-11-25','YYYY-MM-DD'), '123456784', N'Cần Thơ', '0912345674', N'Điều phối viên', NULL)
  INTO NHANVIEN VALUES ('NV005', N'Đặng Thu Hà', N'Nữ', TO_DATE('1975-01-30','YYYY-MM-DD'), '123456785', N'Hải Phòng', '0912345675', N'Bác sĩ/Y sĩ', N'Nội tổng quát')
  INTO NHANVIEN VALUES ('NV006', N'Vũ Hoàng Nam', N'Nam', TO_DATE('1980-04-14','YYYY-MM-DD'), '123456786', N'Huế', '0912345676', N'Bác sĩ/Y sĩ', N'Nội tổng quát')
  INTO NHANVIEN VALUES ('NV007', N'Ngô Thanh Vân', N'Nữ', TO_DATE('1992-07-08','YYYY-MM-DD'), '123456787', N'Quảng Ninh', '0912345677', N'Bác sĩ/Y sĩ', N'Tim mạch')
  INTO NHANVIEN VALUES ('NV008', N'Lý Hùng', N'Nam', TO_DATE('1984-09-19','YYYY-MM-DD'), '123456788', N'Nghệ An', '0912345678', N'Bác sĩ/Y sĩ', N'Tim mạch')
  INTO NHANVIEN VALUES ('NV009', N'Đỗ Mỹ Linh', N'Nữ', TO_DATE('1995-12-05','YYYY-MM-DD'), '123456789', N'Nam Định', '0912345679', N'Bác sĩ/Y sĩ', N'Tiêu hóa')
  INTO NHANVIEN VALUES ('NV010', N'Bùi Tiến Dũng', N'Nam', TO_DATE('1991-02-28','YYYY-MM-DD'), '123456790', N'Thanh Hóa', '0912345680', N'Bác sĩ/Y sĩ', N'Tiêu hóa')
  INTO NHANVIEN VALUES ('NV011', N'Trịnh Kim Chi', N'Nữ', TO_DATE('1987-06-17','YYYY-MM-DD'), '123456791', N'Vũng Tàu', '0912345681', N'Bác sĩ/Y sĩ', N'Thần kinh')
  INTO NHANVIEN VALUES ('NV012', N'Mai Đức Chung', N'Nam', TO_DATE('1960-08-22','YYYY-MM-DD'), '123456792', N'Hà Tây', '0912345682', N'Bác sĩ/Y sĩ', N'Thần kinh')
  INTO NHANVIEN VALUES ('NV013', N'Hồ Ngọc Hà', N'Nữ', TO_DATE('1984-11-25','YYYY-MM-DD'), '123456793', N'Quảng Bình', '0912345683', N'Bác sĩ/Y sĩ', N'Nhi')
  INTO NHANVIEN VALUES ('NV014', N'Sơn Tùng', N'Nam', TO_DATE('1994-07-05','YYYY-MM-DD'), '123456794', N'Thái Bình', '0912345684', N'Bác sĩ/Y sĩ', N'Nhi')
  INTO NHANVIEN VALUES ('NV015', N'Nguyễn Tử Quảng', N'Nam', TO_DATE('1977-03-12','YYYY-MM-DD'), '123456795', N'Hà Nội', '0912345685', N'Kỹ thuật viên', N'Chẩn đoán hình ảnh')
  INTO NHANVIEN VALUES ('NV016', N'Trương Gia Bình', N'Nam', TO_DATE('1956-05-19','YYYY-MM-DD'), '123456796', N'Bình Định', '0912345686', N'Kỹ thuật viên', N'Xét nghiệm')
  INTO NHANVIEN VALUES ('NV017', N'Phạm Nhật Vượng', N'Nam', TO_DATE('1968-08-05','YYYY-MM-DD'), '123456797', N'Hà Tĩnh', '0912345687', N'Kỹ thuật viên', N'Chẩn đoán hình ảnh')
  INTO NHANVIEN VALUES ('NV018', N'Nguyễn Thị Phương Thảo', N'Nữ', TO_DATE('1970-06-07','YYYY-MM-DD'), '123456798', N'Hà Nội', '0912345688', N'Kỹ thuật viên', N'Xét nghiệm')
  INTO NHANVIEN VALUES ('NV019', N'Trần Đình Long', N'Nam', TO_DATE('1961-02-22','YYYY-MM-DD'), '123456799', N'Hải Dương', '0912345689', N'Kỹ thuật viên', N'Siêu âm')
  INTO NHANVIEN VALUES ('NV020', N'Hồ Hùng Anh', N'Nam', TO_DATE('1970-09-28','YYYY-MM-DD'), '123456800', N'Thừa Thiên Huế', '0912345690', N'Kỹ thuật viên', N'X-Quang')
SELECT * FROM dual;

INSERT ALL
  INTO BENHNHAN VALUES ('BN001', N'Nguyễn Văn Khách', N'Nam', TO_DATE('1990-01-01','YYYY-MM-DD'), '001090123451', '10', N'Lý Thường Kiệt', N'Quận 10', N'TP HCM', N'Đau dạ dày', N'Không', NULL)
  INTO BENHNHAN VALUES ('BN002', N'Trần Thị Hoa', N'Nữ', TO_DATE('1985-05-15','YYYY-MM-DD'), '001085123452', '20', N'Cách Mạng Tháng 8', N'Quận 3', N'TP HCM', N'Viêm xoang', N'Tiểu đường', N'Aspirin')
  INTO BENHNHAN VALUES ('BN003', N'Lê Công Vinh', N'Nam', TO_DATE('1985-12-10','YYYY-MM-DD'), '001085123453', '15', N'Trần Hưng Đạo', N'Quận 1', N'TP HCM', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN004', N'Phạm Huỳnh Đông', N'Nam', TO_DATE('1983-04-05','YYYY-MM-DD'), '001083123454', '05', N'Lê Lợi', N'Hà Đông', N'Hà Nội', N'Cao huyết áp', N'Tim mạch', NULL)
  INTO BENHNHAN VALUES ('BN005', N'Đỗ Hải Yến', N'Nữ', TO_DATE('1982-10-20','YYYY-MM-DD'), '001082123455', '101', N'Nguyễn Huệ', N'Quận 1', N'TP HCM', NULL, NULL, N'Penicillin')
  INTO BENHNHAN VALUES ('BN006', N'Vũ Cát Tường', N'Nữ', TO_DATE('1992-10-02','YYYY-MM-DD'), '001092123456', '22', N'Điện Biên Phủ', N'Bình Thạnh', N'TP HCM', N'Hen suyễn', N'Hen suyễn', NULL)
  INTO BENHNHAN VALUES ('BN007', N'Ngô Kiến Huy', N'Nam', TO_DATE('1988-06-29','YYYY-MM-DD'), '001088123457', '88', N'Hùng Vương', N'Hồng Bàng', N'Hải Phòng', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN008', N'Lý Nhã Kỳ', N'Nữ', TO_DATE('1982-07-19','YYYY-MM-DD'), '001082123458', '19', N'Lê Thánh Tôn', N'Quận 1', N'TP HCM', NULL, N'Béo phì', NULL)
  INTO BENHNHAN VALUES ('BN009', N'Đan Trường', N'Nam', TO_DATE('1976-11-29','YYYY-MM-DD'), '001076123459', '29', N'Âu Cơ', N'Tân Bình', N'TP HCM', N'Cận thị', NULL, NULL)
  INTO BENHNHAN VALUES ('BN010', N'Lam Trường', N'Nam', TO_DATE('1974-10-14','YYYY-MM-DD'), '001074123460', '14', N'Phan Đình Phùng', N'Quận Phú Nhuận', N'TP HCM', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN011', N'Mỹ Tâm', N'Nữ', TO_DATE('1981-01-16','YYYY-MM-DD'), '001081123461', '16', N'Hải Châu', N'Hải Châu', N'Đà Nẵng', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN012', N'Đàm Vĩnh Hưng', N'Nam', TO_DATE('1971-10-02','YYYY-MM-DD'), '001071123462', '02', N'Quốc lộ 13', N'Thủ Đức', N'TP HCM', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN013', N'Thu Minh', N'Nữ', TO_DATE('1977-09-22','YYYY-MM-DD'), '001077123463', '22', N'Nam Kỳ Khởi Nghĩa', N'Quận 3', N'TP HCM', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN014', N'Tùng Dương', N'Nam', TO_DATE('1983-09-18','YYYY-MM-DD'), '001083123464', '18', N'Phố Huế', N'Hai Bà Trưng', N'Hà Nội', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN015', N'Hà Anh Tuấn', N'Nam', TO_DATE('1984-12-15','YYYY-MM-DD'), '001084123465', '15', N'Võ Văn Tần', N'Quận 3', N'TP HCM', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN016', N'Uyên Linh', N'Nữ', TO_DATE('1987-12-31','YYYY-MM-DD'), '001087123466', '31', N'Trần Phú', N'Hải Châu', N'Đà Nẵng', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN017', N'Isaac', N'Nam', TO_DATE('1988-06-13','YYYY-MM-DD'), '001088123467', '13', N'Nguyễn Trãi', N'Quận 5', N'TP HCM', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN018', N'Chi Pu', N'Nữ', TO_DATE('1993-06-14','YYYY-MM-DD'), '001093123468', '14', N'Xuân Thủy', N'Cầu Giấy', N'Hà Nội', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN019', N'Đen Vâu', N'Nam', TO_DATE('1989-05-13','YYYY-MM-DD'), '001089123469', '13', N'Hạ Long', N'Hạ Long', N'Quảng Ninh', NULL, NULL, NULL)
  INTO BENHNHAN VALUES ('BN020', N'Suboi', N'Nữ', TO_DATE('1990-01-10','YYYY-MM-DD'), '001090123470', '10', N'Lê Văn Sỹ', N'Quận 3', N'TP HCM', NULL, NULL, NULL)
SELECT * FROM dual;

INSERT ALL
  INTO HSBA VALUES ('BA001', 'BN001', TO_DATE('2024-01-01','YYYY-MM-DD'), N'Đau bao tử', N'Uống thuốc tiêu hóa', 'NV009', 'K01', N'Ổn định')
  INTO HSBA VALUES ('BA002', 'BN002', TO_DATE('2024-01-02','YYYY-MM-DD'), N'Viêm phổi', N'Kháng sinh', 'NV005', 'K02', N'Theo dõi thêm')
  INTO HSBA VALUES ('BA003', 'BN003', TO_DATE('2024-01-03','YYYY-MM-DD'), N'Rối loạn nhịp tim', N'Đặt máy tạo nhịp', 'NV007', 'K03', N'Nhập viện')
  INTO HSBA VALUES ('BA004', 'BN004', TO_DATE('2024-01-04','YYYY-MM-DD'), N'Đau đầu kéo dài', N'Chụp CT', 'NV011', 'K04', N'Chờ kết quả')
  INTO HSBA VALUES ('BA005', 'BN005', TO_DATE('2024-01-05','YYYY-MM-DD'), N'Sốt xuất huyết', N'Truyền dịch', 'NV006', 'K02', N'Nguy hiểm')
  INTO HSBA VALUES ('BA006', 'BN006', TO_DATE('2024-01-06','YYYY-MM-DD'), N'Viêm ruột thừa', N'Mổ nội soi', 'NV010', 'K01', N'Đã mổ')
  INTO HSBA VALUES ('BA007', 'BN007', TO_DATE('2024-01-07','YYYY-MM-DD'), N'Suy tim độ 2', N'Thuốc trợ tim', 'NV008', 'K03', N'Ổn định')
  INTO HSBA VALUES ('BA008', 'BN008', TO_DATE('2024-01-08','YYYY-MM-DD'), N'Tiền đình', N'Nghỉ ngơi', 'NV012', 'K04', N'Cho về')
  INTO HSBA VALUES ('BA009', 'BN009', TO_DATE('2024-01-09','YYYY-MM-DD'), N'Viêm họng hạt', N'Súc miệng nước muối', 'NV013', 'K05', N'Bình thường')
  INTO HSBA VALUES ('BA010', 'BN010', TO_DATE('2024-01-10','YYYY-MM-DD'), N'Ho gà', N'Tiêm chủng', 'NV014', 'K05', N'Ổn định')
  INTO HSBA VALUES ('BA011', 'BN011', TO_DATE('2024-01-11','YYYY-MM-DD'), N'Đau đại tràng', N'Nội soi', 'NV009', 'K01', N'Viêm nhẹ')
  INTO HSBA VALUES ('BA012', 'BN012', TO_DATE('2024-01-12','YYYY-MM-DD'), N'Phế quản', N'Thở khí dung', 'NV005', 'K02', N'Giảm ho')
  INTO HSBA VALUES ('BA013', 'BN013', TO_DATE('2024-01-13','YYYY-MM-DD'), N'Hở van tim', N'Phẫu thuật', 'NV007', 'K03', N'Chờ phẫu thuật')
  INTO HSBA VALUES ('BA014', 'BN014', TO_DATE('2024-01-14','YYYY-MM-DD'), N'Trầm cảm', N'Trị liệu tâm lý', 'NV011', 'K04', N'Cần người thân bên cạnh')
  INTO HSBA VALUES ('BA015', 'BN015', TO_DATE('2024-01-15','YYYY-MM-DD'), N'Dị ứng da', N'Bôi thuốc', 'NV006', 'K02', N'Hết ngứa')
  INTO HSBA VALUES ('BA016', 'BN016', TO_DATE('2024-01-16','YYYY-MM-DD'), N'Kiết lỵ', N'Uống kháng sinh', 'NV010', 'K01', N'Ổn định')
  INTO HSBA VALUES ('BA017', 'BN017', TO_DATE('2024-01-17','YYYY-MM-DD'), N'Thiếu máu cơ tim', N'Thuốc vận mạch', 'NV008', 'K03', N'Theo dõi đặc biệt')
  INTO HSBA VALUES ('BA018', 'BN018', TO_DATE('2024-01-18','YYYY-MM-DD'), N'Mất ngủ', N'Thuốc thảo dược', 'NV012', 'K04', N'Tốt')
  INTO HSBA VALUES ('BA019', 'BN019', TO_DATE('2024-01-19','YYYY-MM-DD'), N'Viêm VA', N'Nạo VA', 'NV013', 'K05', N'Đã xong')
  INTO HSBA VALUES ('BA020', 'BN020', TO_DATE('2024-01-20','YYYY-MM-DD'), N'Viêm tai giữa', N'Nhỏ thuốc', 'NV014', 'K05', N'Ổn định')
SELECT * FROM dual;

INSERT ALL
  INTO HSBA_DV VALUES ('BA001', N'Siêu âm bụng', TO_DATE('2024-01-01','YYYY-MM-DD'), 'NV015', N'Dạ dày có vết loét')
  INTO HSBA_DV VALUES ('BA002', N'Chụp X-Quang phổi', TO_DATE('2024-01-02','YYYY-MM-DD'), 'NV020', N'Phổi mờ')
  INTO HSBA_DV VALUES ('BA003', N'Đo điện tâm đồ', TO_DATE('2024-01-03','YYYY-MM-DD'), 'NV016', N'Nhịp tim chậm')
  INTO HSBA_DV VALUES ('BA004', N'Chụp CT đầu', TO_DATE('2024-01-04','YYYY-MM-DD'), 'NV017', N'Không u')
  INTO HSBA_DV VALUES ('BA005', N'Xét nghiệm máu', TO_DATE('2024-01-05','YYYY-MM-DD'), 'NV018', N'Tiểu cầu thấp')
  INTO HSBA_DV VALUES ('BA006', N'Siêu âm ruột thừa', TO_DATE('2024-01-06','YYYY-MM-DD'), 'NV019', N'Viêm cấp')
  INTO HSBA_DV VALUES ('BA011', N'Nội soi đại tràng', TO_DATE('2024-01-11','YYYY-MM-DD'), 'NV015', N'Bình thường')
  INTO HSBA_DV VALUES ('BA012', N'Xét nghiệm đờm', TO_DATE('2024-01-12','YYYY-MM-DD'), 'NV018', N'Vi khuẩn (+) ')
  INTO HSBA_DV VALUES ('BA013', N'Siêu âm tim Doppler', TO_DATE('2024-01-13','YYYY-MM-DD'), 'NV019', N'Hở van 2 lá')
  INTO HSBA_DV VALUES ('BA014', N'Điện não đồ', TO_DATE('2024-01-14','YYYY-MM-DD'), 'NV016', N'Sóng não bất thường')
  INTO HSBA_DV VALUES ('BA007', N'Đo huyết áp 24h', TO_DATE('2024-01-07','YYYY-MM-DD'), 'NV016', N'Huyết áp cao về đêm')
  INTO HSBA_DV VALUES ('BA008', N'Xét nghiệm nước tiểu', TO_DATE('2024-01-08','YYYY-MM-DD'), 'NV018', N'Bình thường')
  INTO HSBA_DV VALUES ('BA009', N'Nội soi tai mũi họng', TO_DATE('2024-01-09','YYYY-MM-DD'), 'NV015', N'Viêm sưng')
  INTO HSBA_DV VALUES ('BA010', N'Chụp X-Quang xoang', TO_DATE('2024-01-10','YYYY-MM-DD'), 'NV020', N'Xoang sàng mờ')
  INTO HSBA_DV VALUES ('BA015', N'Xét nghiệm dị nguyên', TO_DATE('2024-01-15','YYYY-MM-DD'), 'NV018', N'Dị ứng phấn hoa')
  INTO HSBA_DV VALUES ('BA016', N'Cấy phân', TO_DATE('2024-01-16','YYYY-MM-DD'), 'NV018', N'Vi khuẩn lỵ')
  INTO HSBA_DV VALUES ('BA017', N'Chụp mạch vành', TO_DATE('2024-01-17','YYYY-MM-DD'), 'NV017', N'Hẹp 30%')
  INTO HSBA_DV VALUES ('BA018', N'Đo đa ký giấc ngủ', TO_DATE('2024-01-18','YYYY-MM-DD'), 'NV016', N'Ngưng thở khi ngủ')
  INTO HSBA_DV VALUES ('BA019', N'Nội soi họng', TO_DATE('2024-01-19','YYYY-MM-DD'), 'NV015', N'VA quá phát')
  INTO HSBA_DV VALUES ('BA020', N'Đo thính lực', TO_DATE('2024-01-20','YYYY-MM-DD'), 'NV016', N'Giảm thính lực nhẹ')
SELECT * FROM dual;

INSERT ALL
  INTO DONTHUOC VALUES ('BA001', TO_DATE('2024-01-01','YYYY-MM-DD'), N'Phosphalugel', N'3 gói/ngày')
  INTO DONTHUOC VALUES ('BA002', TO_DATE('2024-01-02','YYYY-MM-DD'), N'Amoxicillin', N'2 viên/ngày')
  INTO DONTHUOC VALUES ('BA003', TO_DATE('2024-01-03','YYYY-MM-DD'), N'Digoxin', N'1 viên/sáng')
  INTO DONTHUOC VALUES ('BA004', TO_DATE('2024-01-04','YYYY-MM-DD'), N'Paracetamol', N'3 viên/ngày')
  INTO DONTHUOC VALUES ('BA005', TO_DATE('2024-01-05','YYYY-MM-DD'), N'Oresol', N'Uống thay nước')
  INTO DONTHUOC VALUES ('BA006', TO_DATE('2024-01-06','YYYY-MM-DD'), N'Alpha Choay', N'4 viên/ngày')
  INTO DONTHUOC VALUES ('BA007', TO_DATE('2024-01-07','YYYY-MM-DD'), N'Enalapril', N'1 viên/ngày')
  INTO DONTHUOC VALUES ('BA008', TO_DATE('2024-01-08','YYYY-MM-DD'), N'Betaserc', N'2 viên/ngày')
  INTO DONTHUOC VALUES ('BA009', TO_DATE('2024-01-09','YYYY-MM-DD'), N'Eugica', N'3 viên/ngày')
  INTO DONTHUOC VALUES ('BA010', TO_DATE('2024-01-10','YYYY-MM-DD'), N'Siro Pectol', N'3 thìa/ngày')
  INTO DONTHUOC VALUES ('BA011', TO_DATE('2024-01-11','YYYY-MM-DD'), N'Maalox', N'2 viên/ngày')
  INTO DONTHUOC VALUES ('BA012', TO_DATE('2024-01-12','YYYY-MM-DD'), N'Salbutamol', N'Xịt khi khó thở')
  INTO DONTHUOC VALUES ('BA013', TO_DATE('2024-01-13','YYYY-MM-DD'), N'Aspirin', N'1 viên/ngày')
  INTO DONTHUOC VALUES ('BA014', TO_DATE('2024-01-14','YYYY-MM-DD'), N'Sertraline', N'1 viên/tối')
  INTO DONTHUOC VALUES ('BA015', TO_DATE('2024-01-15','YYYY-MM-DD'), N'Fexofenadine', N'1 viên/ngày')
  INTO DONTHUOC VALUES ('BA016', TO_DATE('2024-01-16','YYYY-MM-DD'), N'Berberin', N'6 viên/ngày')
  INTO DONTHUOC VALUES ('BA017', TO_DATE('2024-01-17','YYYY-MM-DD'), N'Nitroglycerin', N'Ngậm dưới lưỡi khi đau ngực')
  INTO DONTHUOC VALUES ('BA018', TO_DATE('2024-01-18','YYYY-MM-DD'), N'Mimosa', N'2 viên/tối')
  INTO DONTHUOC VALUES ('BA019', TO_DATE('2024-01-19','YYYY-MM-DD'), N'Hapacol', N'2 gói/ngày')
  INTO DONTHUOC VALUES ('BA020', TO_DATE('2024-01-20','YYYY-MM-DD'), N'Otinum', N'Nhỏ tai 3 lần/ngày')
SELECT * FROM dual;

COMMIT;